### ISSUE TITLE
Rendering with the provided docker commands is not working on Windows 10

### ISSUE THREAD

**Issue by n3amil** [t3docs/docker-render-documentation#14]
I just tried to get rendering working on windows 10 and was not able to get the docker container building the html of a typo3 documentation i was working on (contribution guide).

So i added a simple docker-compose.yml which mounts the document root into the container and executes  f.e. the makehtml command.

Because the Preview for doc files on Github is broken, my idea was that this should be a "no brainer" so people just run "docker-compose up" and the files are getting generated. They have a look and commit the pull request.
I would provide the compose file as  "docker-compose.example.yml" so people can adapt the file for their needs (change the command etc.).

This is how the file looks for me right now:

```
version: '2'
services:
  typo3_contrib:
    image: t3docs/render-documentation:latest
    volumes:
    - ./:/PROJECT:ro
    - ./Documentation-GENERATED-temp:/RESULT
    command: makehtml

```

This works for windows and linux, didnt tested it on mac.

I didnt digged to deep into the dockerfile so this can be optimized for sure. It just works for the moment so i was happy ;)
